
var PLANE_CONSTANTS = {};

PLANE_CONSTANTS.MASS = 500;

PLANE_CONSTANTS.SIZE = 150;

PLANE_CONSTANTS.IDEAL_CAMERA_DISTANCE = PLANE_CONSTANTS.SIZE * 4;

PLANE_CONSTANTS.PITCH = {
  FORCE: PLANE_CONSTANTS.MASS * 500,
  OFFSET: PLANE_CONSTANTS.SIZE * .5
};

PLANE_CONSTANTS.ROLL = {
  FORCE: PLANE_CONSTANTS.MASS * 500,
  OFFSET: PLANE_CONSTANTS.SIZE * .5
};

PLANE_CONSTANTS.LIFT = {
  FORCE: PLANE_CONSTANTS.MASS * 16
};

PLANE_CONSTANTS.PUSH = {
  FORCE: PLANE_CONSTANTS.MASS * 8000
};

PLANE_CONSTANTS.BOOSTER = {
  FORCE: PLANE_CONSTANTS.PUSH.FORCE * 4
};

PLANE_CONSTANTS.BODY = {
  LENGTH: PLANE_CONSTANTS.SIZE * .9,
  THICKNESS: PLANE_CONSTANTS.SIZE * .1
};

PLANE_CONSTANTS.WING = {
  SPAN: PLANE_CONSTANTS.SIZE * 1,
  DEPTH: PLANE_CONSTANTS.SIZE * .2,
  THICKNESS: PLANE_CONSTANTS.SIZE * .02
}

PLANE_CONSTANTS.TAIL = {
  WING: {
    SPAN: PLANE_CONSTANTS.SIZE * .4,
    DEPTH: PLANE_CONSTANTS.SIZE * .1,
    THICKNESS: PLANE_CONSTANTS.SIZE * .02
  },
  RUDDER: {
    SPAN: PLANE_CONSTANTS.SIZE * .1,
    DEPTH: PLANE_CONSTANTS.SIZE * .1,
    THICKNESS: PLANE_CONSTANTS.SIZE * .02
  }
}

export default PLANE_CONSTANTS;
